version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install -g serverless@1.49.0
      - npm install
  build:
    commands:
      - serverless remove
  post_build:
    commands:
      - touch api_destroy.fin
artifacts:
  files:
    - api_destroy.fin
