service:
  name: ${env:SERVICE_NAME}-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${env:STAGE_ENV}
  role: ${env:LAMBDA_ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}

functions:
  hello:
    handler: src/controllers/hellos.hello
    events:
      - http:
          method: get
          path: hello
  init:
    handler: src/controllers/maintenances.init
    events:
      - http:
          method: get
          path: maintenances/init
  create:
    handler: src/controllers/todos.create
    events:
      - http:
          path: todos
          method: post
  list:
    handler: src/controllers/todos.list
    events:
      - http:
          path: todos
          method: get
