service:
  name: ${env:SERVICE_NAME}-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  logs:
    restApi:
      format:
        '{
          "request_id":"$context.requestId",
          "ip": "$context.identity.sourceIp",
          "caller": "$context.identity.caller",
          "user": "$context.identity.user",
          "request_time": "$context.requestTime",
          "http_method": "$context.httpMethod",
          "resource_path": "$context.resourcePath",
          "status": "$context.status",
          "protocol": "$context.protocol",
          "response_length": "$context.responseLength"
        }'
  endpointType: REGIONAL
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${env:STAGE_ENV}
  environment:
    REGION: ${env:REGION}
    DYNAMO_PREFIX : ${env:DYNAMO_PREFIX}
    CORS: ${env:CORS}
    TZ: ${env:TZ}
    USER_POOL_ID: ${env:USER_POOL_ID}
  role: ${env:LAMBDA_ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}

functions:
  authorizer:
    handler: app/http/controllers/auth.authorize
  create:
    handler: app/http/controllers/todos.create
    events:
      - http:
          path: v1/todos
          method: post
          cors: true
          authorizer: authorizer
  list:
    handler: app/http/controllers/todos.list
    events:
      - http:
          path: v1/todos
          method: get
          cors: true
          authorizer: authorizer
  get:
    handler: app/http/controllers/todos.get
    events:
      - http:
          path: v1/todos/{id}
          method: get
          cors: true
          authorizer: authorizer
  update:
    handler: app/http/controllers/todos.update
    events:
      - http:
          path: v1/todos/{id}
          method: put
          cors: true
          authorizer: authorizer
  delete:
    handler: app/http/controllers/todos.destroy
    events:
      - http:
          path: v1/todos/{id}
          method: delete
          cors: true
          authorizer: authorizer
