service:
  name: ${env:SERVICE_NAME}-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${env:STAGE_ENV}
  environment:
    DYNAMO_PREFIX : ${env:DYNAMO_PREFIX}
    CORS: ${env:CORS}
    TZ: ${env:TZ}
  role: ${env:LAMBDA_ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}

functions:
  create:
    handler: app/http/controllers/todos.create
    events:
      - http:
          path: v1/todos
          method: post
          cors: true
  list:
    handler: app/http/controllers/todos.list
    events:
      - http:
          path: v1/todos
          method: get
          cors: true
  get:
    handler: app/http/controllers/todos.get
    events:
      - http:
          path: v1/todos/{id}
          method: get
          cors: true
  update:
    handler: app/http/controllers/todos.update
    events:
      - http:
          path: v1/todos/{id}
          method: put
          cors: true
  delete:
    handler: app/http/controllers/todos.destroy
    events:
      - http:
          path: v1/todos/{id}
          method: delete
          cors: true
