service:
  name: ${env:SERVICE_NAME}-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${env:STAGE_ENV}
  environment:
    DYNAMO_PREFIX : ${env:DYNAMO_PREFIX}
    CORS: ${env:CORS}
    TZ: ${env:TZ}
  role: ${env:LAMBDA_ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}

functions:
  hello:
    handler: src/http/controllers/hellos.hello
    events:
      - http:
          method: get
          path: hello
  create:
    handler: src/http/controllers/todos.create
    events:
      - http:
          path: v1/todos
          method: post
  list:
    handler: src/http/controllers/todos.list
    events:
      - http:
          path: v1/todos
          method: get
  get:
    handler: src/http/controllers/todos.get
    events:
      - http:
          path: v1/todos/{id}
          method: get
  update:
    handler: src/http/controllers/todos.update
    events:
      - http:
          path: v1/todos/{id}
          method: put
  delete:
    handler: src/http/controllers/todos.destroy
    events:
      - http:
          path: v1/todos/{id}
          method: delete
