version: '3'
services:
  serverless:
    build: ./serverless
    tty: true
    environment:
      SERVICE_NAME: 'local-docker'
      STAGE_ENV: 'local'
      LAMBDA_ROLE: 'dummy'
      DEPLOY_BUCKET: 'dummy'
    volumes:
      - ../:/app/
      - ./serverless/node_modules/:/app/node_modules/
      - ./serverless/.serverless/:/app/.serverless/
      - ./serverless/.webpack/:/app/.webpack/
