version: '3'
services:
  serverless:
    build: ./serverless
    tty: true
    ports:
      - 3000:3000
    environment:
      SERVICE_NAME: 'local-docker'
      STAGE_ENV: 'local'
      IS_OFFLINE: 'true'
      REGION: 'ap-northeast-1'
      LAMBDA_ROLE: 'dummy'
      DEPLOY_BUCKET: 'dummy'
      DYNAMO_ENDPOINT: 'http://dynamodb:8000'
      DYNAMO_PREFIX: 'local'
      CORS: '*'
      TZ: 'Asia/Tokyo'
    volumes:
      - ../:/src/
    depends_on:
      - dynamodb
  dynamodb:
    image: instructure/dynamo-local-admin
    ports:
      - 8000:8000
    volumes:
      - ./dynamodb/db:/var/lib/dynamodb
