import { injectable } from "inversify";
import "reflect-metadata";
import DynamoDB from "aws-sdk/clients/dynamodb";
import { Todos as ITodos } from "../usecases/stores/Todos";
import Todo from "../entities/todo";
import {
  attribute,
  autoGeneratedHashKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";
import { DataMapper } from "@aws/dynamodb-data-mapper";

let options = {};
if (process.env.IS_OFFLINE) {
  options = {
    accessKeyId: "key",
    secretAccessKey: "secret",
    region: "localhost",
    endpoint: process.env.DYNAMO_ENDPOINT || "http://localhost:8000"
  };
} else {
  options = {
    region: process.env.REGION
  };
}
const mapper = new DataMapper({
  client: new DynamoDB(options),
  tableNamePrefix: `${process.env.DYNAMO_PREFIX}-`
});

@table("todos")
class TodoRecord {
  @autoGeneratedHashKey()
  id!: string;

  @attribute()
  text!: string;

  @attribute({ defaultProvider: () => false })
  checked!: boolean;

  @attribute({ defaultProvider: () => new Date().getTime() })
  createdAt!: number;

  @attribute({ defaultProvider: () => new Date().getTime() })
  updatedAt!: number;
}

@injectable()
export class Todos implements ITodos {
  public async create(text: string): Promise<Todo> {
    const toSave = Object.assign(new TodoRecord(), { text: text });
    const objectSaved = await mapper.put(toSave);
    console.log("created todo in DynamoDB", objectSaved.text);
    return {
      id: objectSaved.id,
      text: objectSaved.text,
      checked: objectSaved.checked,
      createdAt: objectSaved.createdAt,
      updatedAt: objectSaved.updatedAt
    };
  }

  public async all(): Promise<Todo[]> {
    const iterator = mapper.scan(TodoRecord);
    const todos: Todo[] = [];
    // tslint:disable-next-line
    for await (const record of iterator) {
      todos.push({
        id: record.id,
        text: record.text,
        checked: record.checked,
        createdAt: record.createdAt,
        updatedAt: record.updatedAt
      });
    }
    return todos;
  }

  public async get(id: string): Promise<Todo | {}> {
    const myItem = await mapper.get(
      Object.assign(new TodoRecord(), { id: id })
    );
    return {
      id: myItem.id,
      text: myItem.text,
      checked: myItem.checked,
      createdAt: myItem.createdAt,
      updatedAt: myItem.updatedAt
    };
  }

  public async update(
    id: string,
    text: string,
    checked: boolean
  ): Promise<Todo> {
    const myItem = await mapper.get(
      Object.assign(new TodoRecord(), { id: id })
    );
    myItem.text = text;
    myItem.checked = checked;
    myItem.updatedAt = new Date().getTime();
    const objectSaved = await mapper.update(myItem);
    return {
      id: objectSaved.id,
      text: objectSaved.text,
      checked: objectSaved.checked,
      createdAt: objectSaved.createdAt,
      updatedAt: objectSaved.updatedAt
    };
  }

  public async delete(id: string): Promise<void> {
    await mapper.delete(Object.assign(new TodoRecord(), { id: id }));
  }

  public async createTable(rc: number, wc: number): Promise<void> {
    await mapper.createTable(TodoRecord, {
      readCapacityUnits: rc,
      writeCapacityUnits: wc
    });
  }
}
